// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCompassObjectWidget.h"

void UFGCompassObjectWidget::NativePreConstruct(){ }
void UFGCompassObjectWidget::Tick( FGeometry MyGeometry, float InDeltaTime){ }
void UFGCompassObjectWidget::UpdatePositionInCompass(float halfWidth, FVector2D origin ){ }
void UFGCompassObjectWidget::SetActorRepresentation(  UFGActorRepresentation* actorRepresentation){ }
void UFGCompassObjectWidget::OnCompassObjectAddedToPanel_Implementation( UCanvasPanelSlot* parentSlot){ }
void UFGCompassObjectWidget::OnCompassObjectUpdated_Implementation(){ }
float UFGCompassObjectWidget::GetRepresentationDistanceFromPlayer(){ return float(); }
FVector UFGCompassObjectWidget::GetDirectionFromLocation( FVector location){ return FVector(); }
float UFGCompassObjectWidget::GetAngleFromDirection( FVector direction){ return float(); }
