// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildablePole.h"

AFGBuildablePole::AFGBuildablePole(){ 
	mSnapOnly0 = CreateDefaultSubobject<UFGFactoryConnectionComponent>(TEXT("SnapOnly0"));
	mSnapOnly0->SetupAttachment(RootComponent);
}
void AFGBuildablePole::GetLifetimeReplicatedProps( TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGBuildablePole::BeginPlay(){ }
void AFGBuildablePole::SetPoleHeight( float height){ }
void AFGBuildablePole::SetupConnectionComponent(){ }
void AFGBuildablePole::PostLoad(){ Super::PostLoad(); }
