// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableGeneratorNuclear.h"

void AFGBuildableGeneratorNuclear::GetLifetimeReplicatedProps( TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGBuildableGeneratorNuclear::BeginPlay(){ }
void AFGBuildableGeneratorNuclear::LoadFuel(){ }
bool AFGBuildableGeneratorNuclear::CanLoadFuel() const{ return bool(); }
