// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGEnvironmentSettings.h"

#if WITH_EDITOR
void UFGEnvironmentSettings::PostEditChangeProperty(  FPropertyChangedEvent& propertyChangedEvent){ }
#endif 
UMaterialParameterCollection* UFGEnvironmentSettings::GetWorldBoundsParameters(){ return nullptr; }
